# Generated by Django 5.0.6 on 2026-04-26 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dua",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("title_arabic", models.CharField(blank=True, max_length=200)),
                ("content_arabic", models.TextField()),
                ("translation_tr", models.TextField()),
                ("transliteration", models.TextField(blank=True)),
                ("category", models.CharField(blank=True, max_length=100)),
                ("reference", models.CharField(blank=True, max_length=200)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Dua",
                "verbose_name_plural": "Duas",
                "db_table": "duas",
                "ordering": ["category", "title"],
                "indexes": [
                    models.Index(fields=["category"], name="duas_categor_b4258f_idx"),
                    models.Index(fields=["is_active"], name="duas_is_acti_8bb6c3_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Hadith",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("collection", models.CharField(max_length=50)),
                ("hadith_number", models.CharField(max_length=20)),
                ("arabic_text", models.TextField(blank=True)),
                ("translation_tr", models.TextField()),
                ("chapter", models.CharField(blank=True, max_length=200)),
                ("narrator", models.CharField(blank=True, max_length=100)),
                ("grade", models.CharField(blank=True, max_length=50)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Hadith",
                "verbose_name_plural": "Hadiths",
                "db_table": "hadiths",
                "ordering": ["collection", "hadith_number"],
                "indexes": [
                    models.Index(
                        fields=["collection", "hadith_number"],
                        name="hadiths_collect_cc4efc_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Verse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("verse_key", models.CharField(max_length=20, unique=True)),
                ("chapter_id", models.IntegerField()),
                ("verse_number", models.IntegerField()),
                ("text_uthmani", models.TextField()),
                ("translation_tr", models.TextField()),
                ("chapter_name", models.CharField(blank=True, max_length=100)),
                ("juz_number", models.IntegerField(blank=True, null=True)),
                ("page_number", models.IntegerField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Verse",
                "verbose_name_plural": "Verses",
                "db_table": "verses",
                "ordering": ["chapter_id", "verse_number"],
                "indexes": [
                    models.Index(
                        fields=["chapter_id", "verse_number"],
                        name="verses_chapter_88b308_idx",
                    ),
                    models.Index(
                        fields=["verse_key"], name="verses_verse_k_a324c1_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DailyContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "hadith",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="daily_hadith",
                        to="content.hadith",
                    ),
                ),
                (
                    "verse",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="daily_verse",
                        to="content.verse",
                    ),
                ),
            ],
            options={
                "verbose_name": "Daily Content",
                "verbose_name_plural": "Daily Contents",
                "db_table": "daily_contents",
                "ordering": ["-date"],
            },
        ),
    ]
