# Generated by Django 5.0.6 on 2026-04-26 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserPrayerLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(max_length=100)),
                ("country", models.CharField(default="Türkiye", max_length=100)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "User Prayer Location",
                "verbose_name_plural": "User Prayer Locations",
                "db_table": "user_prayer_locations",
            },
        ),
        migrations.CreateModel(
            name="PrayerTimeCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(max_length=100)),
                ("country", models.CharField(default="Türkiye", max_length=100)),
                ("date", models.DateField()),
                ("imsak", models.CharField(blank=True, max_length=10)),
                ("gunes", models.CharField(blank=True, max_length=10)),
                ("ogle", models.CharField(blank=True, max_length=10)),
                ("ikindi", models.CharField(blank=True, max_length=10)),
                ("aksam", models.CharField(blank=True, max_length=10)),
                ("yatsi", models.CharField(blank=True, max_length=10)),
                ("method", models.IntegerField(default=2)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Prayer Time Cache",
                "verbose_name_plural": "Prayer Time Caches",
                "db_table": "prayer_time_caches",
                "indexes": [
                    models.Index(
                        fields=["city", "date"], name="prayer_time_city_1da682_idx"
                    ),
                    models.Index(fields=["date"], name="prayer_time_date_ed89f0_idx"),
                ],
                "unique_together": {("city", "country", "date")},
            },
        ),
    ]
